name: Genera PDF

on:
  workflow_dispatch

jobs:
  crear-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
